### PR TITLE
Fixes #6

### LINKED ISSUE #6: Add Side Navbar
Add Side Navbar and add categories. 
Refer this link for categories: https://dexty007.github.io/gotservices.github.io/aboutus.html

### PR DESCRIPTION
**Pull request by ritwizsinha**
added a responsive sidebar along with various categories

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@ritwizsinha Attach a screenshot.

**Comment by ritwizsinha** [comment]
Open SIdebar
open

Closed Sidebar
close

**Comment by harsh-jindal** [comment]
LGTM

**Review by harsh-jindal — APPROVED** [review]

**Comment by harsh-jindal** [comment]
@ritwizsinha From next time use destructuring for Component and Fragment while importing from react.

**Comment by ritwizsinha** [comment]
Thanks will take care next time

**Pull request merged**
