### PR TITLE
Added Top Vendors Section

### PR DESCRIPTION
**Pull request by Hardik-Agrawal**
Capture

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@Hardik-Agrawal Travis is failing. Please see the travis logs.

**Comment by harsh-jindal** [comment]
@Hardik-Agrawal Use card of ant design to make cards. Try and see if you can make it circular else make it rectangle.

**Comment by Hardik-Agrawal** [comment]
Working on it

**Comment by harsh-jindal** [comment]
@Hardik-Agrawal Update?

**Comment by Hardik-Agrawal** [comment]
I've got a merging issues I already asked ritwiz to make PR.If he didn't I
will try again tonight

**Comment by harsh-jindal** [comment]
@Hardik-Agrawal Okay

**Comment by Hardik-Agrawal** [comment]
Capture


Screenshot from my latest PR

**Comment by Hardik-Agrawal** [comment]
Capture


Slideshow and Topvendors

**Comment by harsh-jindal** [comment]
@Hardik-Agrawal  Please make it into 4 grid (refer: https://ant.design/components/grid/). Also space the cards equally in the container.
And make sure in the mobile it is one card below the other.
Resolve the conflicts.

**Review by harsh-jindal — APPROVED** [review]

**Pull request merged**
